### ISSUE TITLE
deleteGroupMembers(int groupID)

### ISSUE THREAD

**Issue by xDeerStalker** [KingPin2/VSServer#4]
bitte ändern zu deleteGroupMember(int groupID, int userID)

außerdem: 
usersNotInGroup funktioniert eher suboptimal (hab auf dem Client nen workaround gebaut)
+saveGroup() soll den Moderator als Member in die Gruppe packen
+deleteUser(UserID) benötigt, //onDelete: Cascade bezüglich Messages und Gruppen?
+deleteteGroup(groupID) benötigt //--> onDelete--> was soll passieren?

**Comment by DoBe94** [comment]
deleteGroupMembers ist eigentlich nur für den Server

mach g.removeMember(User) und dann db.saveGroup(g)

Andere Funktionen sind eingebaut.
